#!/usr/bin/env bash

case "$1" in 
	t | test ) cargo test ;;
	test:cmd ) cargo run tags --note_dir testdata/note --note_marker '*' --note_extension '.gnote' --output testdata/tags --cache_dir testdata/cache ;;
	* ) cargo run -- "$@" ;;
esac