#!/usr/bin/env bash

case "$1" in 
	t | test ) cargo test ;;
	t:cmd | test:cmd ) cargo run tags --note-dir testdata/note --note-marker '*' --note-extension '.gnote' --output testdata/tags --cache-dir testdata/cache ;;
	* ) cargo run -- "$@" ;;
esac