#!/usr/bin/env bun

import { app, $ } from "@gutenye/script.js";

app.cmd().add(async ({ argv }) => {
  if (argv.length === 0) {
    await $`yarn start`;
  }
});

app.cmd("t, test", "Run tests").add(async () => {
  await $`yarn test`;
});

app.cmd("t:cmd, test:cmd", "Run test:cmd").add(async () => {
  await $`yarn test:cmd`;
});
