#!/usr/bin/env bash

VERSION=$(cat VERSION)

build() {
  go build -o gnotes
}

build-all() {
  ./build.sh
}

release() {
  #github-release --verbose release --user gutenye --repo gnote-cli --tag $VERSION
  github-release --verbose upload --user gutenye --repo gnote-cli --tag $VERSION --name gnote.homebrew.amd64-$VERSION.tar.gz --file gnote.homebrew.amd64-$VERSION.tar.gz
}

case "$1" in
  build ) build ;;
  release ) release ;;
  build-all ) build-all ;;
esac
