#!/usr/bin/env bun

import { app, $ } from "@gutenye/script.js";
import fs from "node:fs";

const VERSION = fs.readFileSync("VERSION", "utf8").trim();

app.cmd("start", "Run from src").add(async ({ argv }) => {
  await $`go run . ${argv}`.cwd("src");
});

app.cmd("t, test", "Run go tests").add(async () => {
  await $`go test ./...`;
});

app.cmd("t:cmd, test:cmd", "Run tags command on test data").add(async ({ argv }) => {
  await $`go run . tags --note-dir ../testdata/note --note-marker '*' --note-extension '.gnote' --output ../testdata/tags --cache-dir ../testdata/cache --watch ${argv}`.cwd("src");
});

app.cmd("build", "Build binary").add(async () => {
  await $`
    mkdir -p dist
    go build -o dist/gnote
  `;
});

app.cmd("package", "Package macOS tarball").add(async () => {
  await $`tar zcvf macos.tar.gz -C dist .`;
});

app.cmd("publish", "Build, package and upload").add(async () => {
  await app.invoke("build");
  await app.invoke("package");
  // upload to github release
});

app.cmd("release", "Release").add(async () => {
  console.log(`Releasing ${VERSION}`);
});

app.cmd("build-all", "Run build.sh").add(async () => {
  await $`./build.sh`;
});
