#!/usr/bin/env bash

VERSION=$(cat VERSION)

cmd="$1"
shift

main() {
  case "$cmd" in
    start ) start "$@" ;;
    t | test ) go test ./... ;;
    t:cmd | test:cmd ) start tags --note-dir ../testdata/note --note-marker '*' --note-extension '.gnote' --output ../testdata/tags --cache-dir ../testdata/cache "$@" ;; 
    publish ) publish ;;
    build ) build ;;
    release ) release ;;
    build-all ) build-all ;;
  esac
}

start() {
  cd src && go run . "$@"
}

publish() {
  build
  package
  # upload to github release
}


build() {
  mkdir -p dist
  go build -o dist/gnote
}

package() {
  tar zcvf macos.tar.gz -C dist  .
}


build-all() {
  ./build.sh
}


main "$@"
