name: Gnote (Rust)

on: 
  push: 
    paths:
      - gnote.rs/**

defaults:
  run:
    working-directory: gnote.rs

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: gnote.rs
      - run: cargo test
