name: Release (Rust)

env:
  ROOT: gnote.rs

on:
  workflow_dispatch:
  push:
    paths:
      - gnote.rs/**
    tags: 
      - rs*.*.*

defaults:
  run:
    working-directory: gnote.rs

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
          - x86_64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{matrix.target}}
      - name: Cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ${{env.ROOT}}
      - name: Install Cross
        run: cargo install cross
      - name: Build
        run: cargo build --release --target ${{matrix.target}} && mv target/${{matrix.target}}/release/gnote gnote.rs-linux-amd64-v1.0.0
      # - uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       ${{env.ROOT}}/gnote.rs-macos-arm64-v1.0.0