name: Release (Rust)

env:
  name: gnote.rs

on:
  workflow_dispatch:
  push:
    paths:
      - gnote.rs/**
    tags: 
      - rs*.*.*

defaults:
  run:
    working-directory: gnote.rs

jobs:
  release:
    name: Release (${{matrix.platform}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-amd64
          - os: macos-latest
            platform: macos-amd64
          - os: macos-latest
            platform: macos-arm64
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - name: Set VERSION
        run: echo VERSION=${GITHUB_REF_NAME#rs} >> $GITHUB_ENV
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ${{env.name}}
      - name: Build
        run: cargo build --release 
        if: ${{matrix.platform}} != macos-arm64
      - name: Build (macos-arm64)
        run: >
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path)
          MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)
          cargo build --target=aarch64-apple-darwin &&
          mv target/aarch64-apple-darwin/release/gnote target/release/gnote
        if: ${{matrix.platform}} == macos-arm64
      - name: Upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{env.name}}/target/release/gnote
          asset_name: gnote.rs-${{matrix.platform}}-v${{env.VERSION}}
          tag: ${{github.ref_name}}
          repo_token: ${{secrets.GITHUB_TOKEN}}
          release_name: ${{env.name}} v${{env.VERSION}}