name: Release (Rust)

env:
  ROOT: gnote.rs

on:
  workflow_dispatch:
  push:
    paths:
      - gnote.rs/**
    tags: 
      - rs*.*.*

defaults:
  run:
    working-directory: gnote.rs

jobs:
  release:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ${{env.ROOT}}
      - name: Build
        run: >
          cargo build --release &&
          mv target/release/gnote gnote.rs-linux-amd64-v1.0.0
      # - uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       ${{env.ROOT}}/gnote.rs-macos-arm64-v1.0.0