name: ReleaseRs

on:
  push:
    paths:
      - gnote.rs/**
    tags: 
      - "rs*.*.*"

defaults:
  run:
    working-directory: gnote.rs

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: gnote.rs
      - run: cargo build --release && mv target/release/gnote target/release/gnote.ts-macos-arm64-v1.0.0
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            gnote.rs/target/release/gnote.ts-macos-arm64-v1.0.0
