name: Release (Rust)

env:
  ROOT: gnote.rs

on:
  workflow_dispatch:
  push:
    paths:
      - gnote.rs/**
    tags: 
      - rs*.*.*

defaults:
  run:
    working-directory: gnote.rs

jobs:
  release:
    name: Release for ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-amd64
          - os: macos-latest
            platform: macos-amd64
    steps:
      - uses: actions/checkout@v2
      - name: Set VERSION
        run: echo VERSION=${GITHUB_REF_NAME#rs} >> $GITHUB_ENV
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ${{env.ROOT}}
      - name: Build
        run: cargo build --release 
      - name: Upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/release/gnote
          asset_name: gnote.rs-${{matrix.platform}}-v${{env.VERSION}}
          tag: ${{github.refname}}

