name: ReleaseRs

on:
	push:
		tags: 
			- "rs*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
			- uses: Swatinem/rust-cache@v1
				with:
					working-directory: 
      - run: cargo build --release && mv target/release/gnote target/release/gnote.ts-macos-arm64-v1.0.0
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/gnote.ts-macos-arm64-v1.0.0
