name: ReleaseRs

env:
  ROOT: gnote.rs

on:
  push:
    paths:
      - ${{env.ROOT}}/**
    tags: 
      - rs*.*.*

defaults:
  run:
    working-directory: ${{env.ROOT}}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ${{env.ROOT}}
      - run: cargo build --release && mv target/release/gnote target/release/gnote.rs-macos-arm64-v1.0.0
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{env.ROOT}}/target/release/gnote.rs-macos-arm64-v1.0.0
